services:
  - type: web
    name: n8n-automation
    runtime: docker
    plan: starter
    region: oregon
    image:
      url: n8nio/n8n:latest
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: sqlite
      - key: DB_SQLITE_DATABASE
        value: /data/.n8n/database.sqlite
      - key: N8N_USER_FOLDER
        value: /data/.n8n
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n-automation
          property: host
      - key: N8N_METRICS
        value: true
      - key: DB_SQLITE_VACUUM_ON_STARTUP
        value: true
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 1
